name: 新功能请求
description: 提出一项新的功能。
title: 在这里输入你的标题
labels: ["新功能", "待查看"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您贡献您的想法。请在上面的文本框⬆️起一个能够清晰概括此功能的标题，便于管理者了解您的想法。
        
        > [!important]
        > 重要：如果您想要提出**多项功能**，请为每一个功能发起一个单独的 Issue 。
        >
        > 由于管理者时间精力有限，提交的功能请求可能需要比较久的时间才能实现。
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 在开始反馈这个问题之前，请先检查：
      options:
        - label: 我已更新到最新版 [Release](https://github.com/WilsonHuangDev/bsdnsxx-classisland-mgmt-cfg/releases/latest) ，确认我想要的功能还没有实现。
          required: true
        - label: 我已在 [Issues](https://github.com/WilsonHuangDev/bsdnsxx-classisland-mgmt-cfg/issues?q=label%3A新功能) 中检索，确认我想要的功能未被提交过。
          required: true
        - label: 该功能是与北京师范大学南山附属学校 ClassIsland 集控相关的，不是 ClassIsland 软件本体的新功能。
          required: true
        - label: 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。
          required: true
  - type: textarea
    id: back
    attributes:
      label: 理由
      description: 添加此功能的理由。
    validations:
      required: true
  - type: textarea
    id: req
    attributes:
      label: 想要实现的功能
      description: 请详细描述一下您想要的功能，描述越具体，采纳的可能性越高。
    validations:
      required: true
  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步
      description: 回顾您的回答
      options:
        - label: 我认为上述描述已经足够详细，以便开发人员理解您想要的功能。如果我的 Issue 没有按照上述要求填写，可能会被无条件关闭。
          required: true
