name: Package and Release

on:
  workflow_dispatch:

jobs:
  Package:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Package m2022-01/ClassIsland folder
      run: |
        cd m2022-01
        Compress-Archive -Path ./ClassIsland -DestinationPath ../ClassIsland-91.zip
        echo 'Successfully packaged "ClassIsland-91".'

    - name: Upload ClassIsland-91.zip
      uses: actions/upload-artifact@v4
      with:
        name: 'ClassIsland-91'
        path: 'ClassIsland-91.zip'

    - name: Package m2022-05/ClassIsland folder
      run: |
        cd m2022-05
        Compress-Archive -Path ./ClassIsland -DestinationPath ../ClassIsland-95.zip
        echo 'Successfully packaged "ClassIsland-95".'

    - name: Upload ClassIsland-95.zip
      uses: actions/upload-artifact@v4
      with:
        name: 'ClassIsland-95'
        path: 'ClassIsland-95.zip'

    - name: Package m2022-06/ClassIsland folder
      run: |
        cd m2022-06
        Compress-Archive -Path ./ClassIsland -DestinationPath ../ClassIsland-96.zip
        echo 'Successfully packaged "ClassIsland-96".'

    - name: Upload ClassIsland-96.zip
      uses: actions/upload-artifact@v4
      with:
        name: 'ClassIsland-96'
        path: 'ClassIsland-96.zip'
      
    - name: Package m2022-08/ClassIsland folder
      run: |
        cd m2022-08
        Compress-Archive -Path ./ClassIsland -DestinationPath ../ClassIsland-98.zip
        echo 'Successfully packaged "ClassIsland-98".'

    - name: Upload ClassIsland-98.zip
      uses: actions/upload-artifact@v4
      with:
        name: 'ClassIsland-98'
        path: 'ClassIsland-98.zip'

    - name: Package m2023-05/ClassIsland folder
      run: |
        cd m2023-05
        Compress-Archive -Path ./ClassIsland -DestinationPath ../ClassIsland-85.zip
        echo 'Successfully packaged "ClassIsland-85".'

    - name: Upload ClassIsland-85.zip
      uses: actions/upload-artifact@v4
      with:
        name: 'ClassIsland-85'
        path: 'ClassIsland-85.zip'

    - name: Package Tools folder
      run: |
        cd Tools
        Compress-Archive -Path * -DestinationPath ../Tools.zip
        echo 'Successfully packaged "Tools".'

    - name: Upload Tools.zip
      uses: actions/upload-artifact@v4
      with:
        name: 'Tools'
        path: 'Tools.zip'
        
  Release:
    runs-on: windows-latest
    
    needs:
      - Package
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make release dir
        run: mkdir -p release

      - name: Download Build Artifact ClassIsland-91
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-91
          path: release

      - name: Download Build Artifact ClassIsland-95
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-95
          path: release

      - name: Download Build Artifact ClassIsland-96
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-96
          path: release

      - name: Download Build Artifact ClassIsland-98
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-98
          path: release

      - name: Download Build Artifact ClassIsland-85
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-85
          path: release

      - name: Download Build Artifact Tools
        uses: actions/download-artifact@v4.1.8
        with:
          name: Tools
          path: release

      - name: Calculate checksums
        run: pwsh .github/workflows/generate-sha256.ps1 release/

      - name: Print files from release dir
        run: ls release -Recurse -Force

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: release/*.zip
          draft: true
          bodyFile: release/checksums.md
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
