name: Package and Release

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main

jobs:
  Package:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload ClassIsland-91.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-91
        path: |
          m2022-01/
          !m2022-01/*.json
        compression-level: 9
        overwrite: true

    - name: Upload ClassIsland-95.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-95
        path: |
          m2022-05/
          !m2022-05/*.json
        compression-level: 9
        overwrite: true

    - name: Upload ClassIsland-96.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-96
        path: |
          m2022-06/
          !m2022-06/*.json
        compression-level: 9
        overwrite: true

    - name: Upload ClassIsland-98.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-98
        path: |
          m2022-08/
          !m2022-08/*.json
        compression-level: 9
        overwrite: true

    - name: Upload ClassIsland-85.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-85
        path: |
          m2023-05/
          !m2023-05/*.json
        compression-level: 9
        overwrite: true

    - name: Upload Tools.zip
      uses: actions/upload-artifact@v4
      with:
        name: Tools
        path: Tools
        compression-level: 9
        overwrite: true

  Release:
    runs-on: ubuntu-latest
    
    needs:
      - Package
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make release dir
        run: mkdir release

      - name: Download Build Artifact ClassIsland-91
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-91
          path: release

      - name: Download Build Artifact ClassIsland-95
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-95
          path: release

      - name: Download Build Artifact ClassIsland-96
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-96
          path: release

      - name: Download Build Artifact ClassIsland-98
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-98
          path: release

      - name: Download Build Artifact ClassIsland-85
        uses: actions/download-artifact@v4.1.8
        with:
          name: ClassIsland-85
          path: release

      - name: Download Build Artifact Tools
        uses: actions/download-artifact@v4.1.8
        with:
          name: Tools
          path: release

      - name: Print files from release dir
        run: |
          ls -lah release

      - name: Create a Draft Release
        uses: wangliang181230/github-action-ghr@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GHR_PATH: release/
          GHR_TITLE: ${{ github.ref_name }}
          GHR_REPLACE: true
          GHR_DRAFT: true
          
