name: Package ClassIsland Folders to Zip

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main

jobs:
  Package_m2022-01:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload ClassIsland-91.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-91
        path: |
          m2022-01/
          !m2022-01/*.json
        compression-level: 8
        
  Package_m2022-05:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload ClassIsland-95.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-95
        path: |
          m2022-05/
          !m2022-05/*.json
        compression-level: 8

  Package_m2022-06:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload ClassIsland-96.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-96
        path: |
          m2022-06/
          !m2022-06/*.json
        compression-level: 8

  Package_m2022-08:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Upload ClassIsland-98.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-98
        path: |
          m2022-08/
          !m2022-08/*.json
        compression-level: 8

  Package_m2023-05:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload ClassIsland-85.zip
      uses: actions/upload-artifact@v4
      with:
        name: ClassIsland-85
        path: |
          m2023-05/
          !m2023-05/*.json
        compression-level: 8

  Package_Tools:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload Tools.zip
      uses: actions/upload-artifact@v4
      with:
        name: Tools
        path: Tools
        compression-level: 8
